### ISSUE TITLE
Изучить предложенные Димой источники

### ISSUE THREAD

**Issue by Konohomaru** [Konohomaru/Gira#12]
- [x] Прочитать [эту статью](https://martinfowler.com/). Мартин Фаулер о командной работе.
- [x] Изучить [диаграмму Miro](https://miro.com/app/board/o9J_kvElAWc=/).
- [x] Что [это за компания](https://www.thoughtworks.com/)? Сайт должен ответить на вопрос.
- [x] Полистать [эту книгу](https://www.amazon.com/Accelerate-Software-Performing-Technology-Organizations/dp/1942788339). Кажется метрики как в этой книге будут и у нас.
- [x] [Битая ссылка](https://sci-hub.se/) на бесплатный дистрибьютер научной литературы.

---

### DoD:
На [доске Miro](https://miro.com/app/board/o9J_ldgWiJk=/) должны появиться метрики, которые мы будем показывать пользователям.

**Comment by Konohomaru** [comment]
> Архитектура программного обеспечения должна быть готова к изменениям. Выпуская продукт на рынок, нельзя наверняка знать как им будут пользоваться люди. От пользователей можно получать обратную связь и делать выводы о том что и как требуется вырезать, добавить, улучшить или изменить. Чтобы быть готовым к такому круговороту программной разработки, как зарекомендовавший себя вариант, можно наладить CI/CD. Придерживаться Agile методологии. Настроить автоматическое тестирование, чтобы не привносить ошибки в обновления программного продукта. И время от времени проводить рефакторинг кода.

Мартин Фаулер на [martinfowler.com](https://martinfowler.com/) (дата обращения: 07.01.2021)

**Comment by Konohomaru** [comment]
> Современный Agile сильно изменился от того, что описывали пионеры данного подхода. Мартин Фаулер видит суть гибкого мышления в двух контрастах: Agile является адаптивным, а не прогностическим и Agile ориентирован на людей, а не на процесс.

Мартин Фаулер на [martinfowler.com](https://martinfowler.com/agile.html) (дата обращения: 07.01.2021)

**Comment by Konohomaru** [comment]
> Мартин Фаулер разделяет CI на следующие важные части: поддержка единого репозитория, автоматическая сборка, сборка автоматически тестируется, каждый может коммитить в репозиторий каждый день, каждый коммит собирается на интеграционной машине, ломающие коммиты быстро исправляются, сборка всегда остаётся быстрой, тестирование на копии продакшена, каждый легко получает актуальный исполняемый файл, каждый видит что происходит в CI, автоматизированная выкладка на машины.

Мартин Фаулер на [martinfowler.com](https://martinfowler.com/articles/continuousIntegration.html) (дата обращения: 07.01.2021)

**Comment by Konohomaru** [comment]
Пример реализации [Four Keys Metrics](https://www.thoughtworks.com/radar/techniques/four-key-metrics) на GitHub (open source): [RedGate.Metrics](https://github.com/red-gate/RedGate.Metrics).

**Comment by Konohomaru** [comment]
**Sprint Velocity.** Данная метрика показывает какими именно типами задач (полосами в терминологии Mindbox) и в каком количестве занималась команда разработчиков в течении спринта. На данный момент определено три типа задач: bugs, road map, tech debt.

**Comment by Konohomaru** [comment]
**Sprint burndown.** Метрика для того, чтобы наглядно видеть сколько задач было запланировано на спринт, сколько из них в работе и сколько уже выполнены в момент просмотра.

**Comment by Konohomaru** [comment]
**Task cycle time.** Покажет сколько времени нужно задачам, чтобы пройти путь от возникновения до её закрытия. Связав со story point получим статистическое соотношение сложности задачи ко времени её выполнения. Будет полезно для _тимлида_.

**Comment by Konohomaru** [comment]
**Epics burndown across teams.** Тоже самое, что и Sprint Burndown, только для всех команд проекта и для больших (epic) задач. Если большие (epic) задачи сопоставимы с вехами road map, то данная метрика покажет текущее состоянии проекта. Может быть полезно для стейкхолдера.

**Comment by Konohomaru** [comment]
[ThoughtWorks](https://www.thoughtworks.com/) занимается консультированием проблем архитектуры, налаживания бизнес-процессов и прочего в компаниях. На сайте есть полезные статьи об этом. [Мартин Фаулер](https://martinfowler.com/) работает с ними.

**Comment by Konohomaru** [comment]
**4 key metrics**: delivery lead time, deployment frequency, time to restore service, and change fail rate.

**Comment by Konohomaru** [comment]
Возможно [sci-hub.do](https://sci-hub.do/) есть тот самый сайт?
